// Do not edit this file. It defines the canvas for every mode.
// All creative work belongs in Graphics.tsx.
//
// The composition only ever renders the graphics at source resolution.
// The source video is never rendered here; ffmpeg stitches it in afterwards.
import React from 'react';
import {AbsoluteFill} from 'remotion';
import {Graphics} from './Graphics';
import type {JobMeta} from './types';

const PANEL_BACKGROUND = '#0b0e17';

export const Layout: React.FC<{meta: JobMeta}> = ({meta}) => {
  const stacked = meta.mode === 'video-top' || meta.mode === 'video-bottom';
  return (
    // 'separate' keeps a transparent background for the alpha render.
    <AbsoluteFill style={stacked ? {backgroundColor: PANEL_BACKGROUND} : undefined}>
      <Graphics />
    </AbsoluteFill>
  );
};
